# Generated by Django 5.2.7 on 2025-10-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Urunler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isim", models.CharField(max_length=100)),
                ("fiyat", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "kisa_aciklama",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("aciklama", models.TextField(blank=True, null=True)),
                ("seo_title", models.CharField(blank=True, max_length=100, null=True)),
                ("seo_description", models.TextField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, max_length=100, null=True)),
                ("aktifmi", models.BooleanField(default=True)),
                ("resim", models.ImageField(blank=True, null=True, upload_to="")),
                ("tarih", models.DateTimeField(auto_now_add=True)),
                ("anasayfa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Urun",
                "verbose_name_plural": "Urunler",
            },
        ),
    ]
