# Generated by Django 5.2.7 on 2025-10-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urunler", "0002_urunler_kullanici"),
    ]

    operations = [
        migrations.CreateModel(
            name="Markalar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isim", models.CharField(max_length=100)),
                ("aciklama", models.CharField(blank=True, max_length=100, null=True)),
                ("seo_title", models.CharField(blank=True, max_length=100, null=True)),
                ("seo_description", models.TextField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, max_length=100, null=True)),
                ("aktifmi", models.BooleanField(default=True)),
                (
                    "resim",
                    models.ImageField(
                        blank=True, null=True, upload_to="markaresimleri"
                    ),
                ),
            ],
            options={
                "verbose_name": "Markalar",
                "verbose_name_plural": "Markalar",
            },
        ),
        migrations.AlterField(
            model_name="urunler",
            name="resim",
            field=models.ImageField(blank=True, null=True, upload_to="urunresimleri"),
        ),
    ]
