# Generated by Django 5.2.7 on 2025-10-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urunler", "0003_markalar_alter_urunler_resim"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kategoriler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isim", models.CharField(max_length=100)),
                ("aciklama", models.CharField(blank=True, max_length=100, null=True)),
                ("seo_title", models.CharField(blank=True, max_length=100, null=True)),
                ("seo_description", models.TextField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, max_length=100, null=True)),
                ("aktifmi", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Kategori",
                "verbose_name_plural": "Kategoriler",
            },
        ),
    ]
