# Generated by Django 5.2.7 on 2025-10-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urunler", "0004_kategoriler"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kategoriler",
            name="aciklama",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="markalar",
            name="aciklama",
            field=models.TextField(blank=True, null=True),
        ),
    ]
