# Generated by Django 5.2.7 on 2025-10-16 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urunler", "0005_alter_kategoriler_aciklama_alter_markalar_aciklama"),
    ]

    operations = [
        migrations.AddField(
            model_name="urunler",
            name="kategori",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="urunler.kategoriler",
            ),
        ),
        migrations.AddField(
            model_name="urunler",
            name="marka",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="urunler.markalar",
            ),
        ),
    ]
