# Generated by Django 5.2.7 on 2025-10-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urunler", "0006_urunler_kategori_urunler_marka"),
    ]

    operations = [
        migrations.AddField(
            model_name="urunler",
            name="indirimli_fiyat",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
